menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/ViterbiDevelopment/FileShare

favicon: /favicon.jpeg
logo: /favicon.jpeg
title: ViterbiDevelopment

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
